### ISSUE TITLE
How to compile this project

### ISSUE THREAD

**Issue by hzshang** [FlorianRappl/Mario5TS#6]
`gulp` seems not work on current version, can you update the README.md file?

**Comment by FlorianRappl** [comment]
Thanks for the reminder. Any PR on this welcome!

As for all Node.js projects looking at the project.json can be helpful (https://github.com/FlorianRappl/Mario5TS/blob/master/package.json). In this case either `npm start` (live server) or `npm run build` (prod build) should do.

Hope that helps!
